apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend-deployment
  labels:
    app: svc-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-users
  template:
    metadata:
      labels:
        app: svc-users
    spec:
      containers:
        - name: users-backend
          image: okteto.dev/svc-users
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: users-env-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: users-backend-service
spec:
  selector:
    app: svc-users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
