name: Integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ '*' ]
jobs:
    integration:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                node-version: 'latest'
            - name: Install dependencies
              run: npm install
            - name: Run Lint
              run: npm run lint
            - name: Run Unit Tests
              run: npm test
            - name: Run Funcional Tests
              run: npm run test:e2e
            - name: Generate Coverage
              run: npm run test:cov
            - name: Upload Coverage
              uses: codecov/codecov-action@v3